import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Header from '../components/Header/Header';
import Banner from '../components/Banner/Banner';


export default function Home() {
  return (
    <>
      <Head>
        <title>CRM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <Header />
      <Banner />
    </>
  )
}
